### ISSUE TITLE
Radio app prevents scrolling in nextcloud dashboard 

### ISSUE THREAD

**Issue by EmJotGeh** [q4z1/nextcloud-app-radio#1]
https://github.com/nextcloud/server/issues/34732#issue-1418729529

**Comment by q4z1** [comment]
This is only a fork of the official nextcloud radio-app https://git.project-insanity.org/onny/nextcloud-app-radio Feel free to use it on your own risk - I did do some additions which you can examine in my commits.

About this issue: I cannot confirm - check my reply here: https://github.com/nextcloud/server/issues/34732
